### ISSUE TITLE
 ElasticSearchPlatform is not configured properly

### ISSUE THREAD

**Issue by gevera** [nextcloud/fulltextsearch_elasticsearch#11]
Just have installed latest Nextcloud 13

Followed instructions. Everything went smooth. However, there are errors in the log and I can't seem to get

`

Warning | fulltextsearch | Your ElasticSearchPlatform is not configured properly
-- | -- | --

`

`

Error | PHP | include(): Failed opening 'fulltextsearch_elasticsearch/lib/admin.php' for inclusion (include_path='/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/apps') at /var/www/nextcloud/lib/private/legacy/app.php#706
-- | -- | --

`

`

Error | PHP | include(fulltextsearch_elasticsearch/lib/admin.php): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/legacy/app.php#706
-- | -- | --

`

Full log here 
[nextcloud_elasticsearch.log](https://github.com/nextcloud/fulltextsearch_elasticsearch/files/1700831/nextcloud_elasticsearch.log)

Please, help. I can't get this work and it is frustrating

**Comment by daita** [comment]
this should be fixed next release

**Comment by gevera** [comment]
This was the answer a month ago when I have tried it on 12 release.  I've been told it will be fixed in the next release. 

https://github.com/nextcloud/fulltextsearch_elasticsearch/issues/9

**Comment by simpleauthority** [comment]
Is this still an issue? I'm getting this now in NextCloud 13...

**Comment by gevera** [comment]
Are you getting the issue or you are able to implement Elasticsearch?

**Comment by simpleauthority** [comment]
@gevera It ended up working. Sorry I'm just now getting to you
