### ISSUE TITLE
Problem with LDAP Integration and fulltextsearch

### ISSUE THREAD

**Issue by steveknoefler** [nextcloud/fulltextsearch_elasticsearch#12]
Hi,

there is a problem with AD Users and the new fulltextsearch elastic.
Indexing is working but there is no result in the web ui.
local users are working.

if I test it with GET http://192.168.1.10:9200/_search?q=word on cmd I get a result. I guess a problem with the searchbar.

thanks
Steve

**Comment by steveknoefler** [comment]
<img width="921" alt="searchbar" src="https://user-images.githubusercontent.com/13857839/36170821-d5a33254-1100-11e8-81ad-10757c3ea93d.png">


root@nextcloud:/var/www/nextcloud# sudo -u www-data ./occ fulltextsearch:check --json
{
    "fulltextsearch": {
        "version": "0.6.0",
        "config": {
            "search_platform": "OCA\\FullTextSearch_ElasticSearch\\Platform\\ElasticSearchPlatform",
            "index_chunk": "1000",
            "app_navigation": "0",
            "provider_indexed": "{\"files\":\"1\"}"
        }
    },
    "platform": {
        "elastic_search": {
            "class": "OCA\\FullTextSearch_ElasticSearch\\Platform\\ElasticSearchPlatform",
            "version": "0.6.0",
            "config": {
                "elastic_host": "http:\/\/localhost:9200",
                "elastic_index": "my_index"
            }
        }
    },
    "providers": {
        "files": {
            "version": "0.6.0",
            "config": {
                "files_local": "1",
                "files_external": "0",
                "files_encrypted": "0",
                "files_federated": "0",
                "files_size": "20",
                "files_pdf": "1",
                "files_office": "1",
                "files_image": "0",
                "files_audio": "0"
            }
        }
    }
}
root@nextcloud:/var/www/nextcloud#

**Comment by daita** [comment]
### let's see what you have in your index:

- Try to get the ID of one of your file (if possible a text file), using the 'Copy Direct Link' icon when opening the details of the file (_https://cloud.artificial-owl.com/f/4265_ -> ID=4265)
- request the entry on elasticsearch: http://localhost:9200/my_index/standard/files:4265
- send me the result by mail: maxence@nextcloud.com (you can remove the 'content' value)

### now the request:
- check your apache log when you're doing a search request

example:
```
127.0.0.1 - - [13/Feb/2018:19:11:03 -0100] "GET /index.php/apps/fulltextsearch/v1/search?request=%7B%22providers%22%3A%22files%22%2C%22search%22%3A%22test%22%2C%22page%22%3A1%2C%22options%22%3A%7B%22files_local%22%3A%22%22%2C%22files_external%22%3A%22%22%2C%22files_extension%22%3A%22%22%7D%2C%22size%22%3A20%7D HTTP/1.1" 201 3833
```

- paste the url in your browser with the host of your cloud, and replace `/v1/search?request` by `/v1/remote?request=`

example:
```
https://cloud.example.net/index.php/apps/fulltextsearch/v1/remote?request=%7B%22providers%22%3A%22files%22%2C%22search%22%3A%22test%22%2C%22page%22%3A1%2C%22options%22%3A%7B%22files_local%22%3A%22%22%2C%22files_external%22%3A%22%22%2C%22files_extension%22%3A%22%22%7D%2C%22size%22%3A20%7D
```

Please send me the result as well

**Comment by steveknoefler** [comment]
I send it to you

**Comment by morph027** [comment]
Can confirm the problem....

## ES index

```json
{
  "_index" : "nextcloud_fulltextsearch",
  "_type" : "standard",
  "_id" : "files:897",
  "_version" : 2,
  "found" : true,
  "_source" : {
    "owner" : "348791E3-9FE1-405A-B038-D35B4A67C501",
    "attachment" : {
      "date" : "2016-10-13T07:11:00Z",
      "content_type" : "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "language" : "is",
      "content_length" : 8
    },
    "provider" : "files",
    "groups" : [ ],
    "circles" : [ ],
    "share_names" : {
      "348791E3-9FE1-405A-B038-D35B4A67C501" : "Test.docx"
    },
    "users" : [ ],
    "content" : "Foobar!",
    "tags" : [
      "local"
    ]
  }
}
```

## Search query

`https://cloud.example.com/apps/fulltextsearch/v1/search?remote=%7B%22providers%22%3A%22files%22%2C%22search%22%3A%22Foobar%22%2C%22page%22%3A1%2C%22options%22%3A%7B%22files_local%22%3A%22%22%2C%22files_external%22%3A%22%22%2C%22files_extension%22%3A%22%22%7D%2C%22size%22%3A20%7D`

Gives just **CSRF check failed**

**Comment by daita** [comment]
should be fixed in 0.6.1

**Comment by steveknoefler** [comment]
Thanks for Update but error is Not gone:(
No fulltextsearch for ad users

**Comment by steveknoefler** [comment]
Stop
After reindexing it works 

Thanks

**Comment by morph027** [comment]
Jip, works! Thank you 👍
