### ISSUE TITLE
Table 'nextcloud.oc_fulltextsearch_ticks' doesn't exist 

### ISSUE THREAD

**Issue by Omaha2002** [nextcloud/fulltextsearch_elasticsearch#126]
I did a reinstall of elasticsearch conform these instructions:
- deactivate and remove all fulltextsearch apps from NC
- drop both fulltextsearch tables from database (via cPanel / phpMyAdmin)
- systemctl stop elasticsearch (ssh root@…)
- delete /var/lib/elasticsearch/nodes/0
- systemctl start elasticsearch
- download and activate all fulltextsearch apps
- configure fulltextsearch
- ssh to your nextcloud (not root), occ fulltextsearch:stop, :reset, :test (ok); :index

But I'm getting:

![image](https://user-images.githubusercontent.com/3179748/102607820-3dba0d80-4129-11eb-914a-63d1f7cfd5cb.png)

I understand that I'm missing the right tables, how to let elasticsearch re-create them again?

**Comment by Omaha2002** [comment]
Still having this issue, deleted elastic and all other apps and deleted tables, still these errors. Anybody with a hint?

**Comment by thefriendlynet** [comment]
Combining the instructions from these two posts fixes the issue:

https://help.nextcloud.com/t/xml-files-indexing-in-fulltextsearch-elasticsearch/48458/2
https://help.nextcloud.com/t/recreating-fulltextsearch-database-tables/111087

Specifically after the 6 cleanup steps in the first post, including dropping the oc_fulltextsearch_ticks and oc_fulltextsearch tables in mysql, don't forget to delete these as well:
 
DELETE FROM oc_migrations WHERE app='fulltextsearch';
DELETE FROM oc_preferences WHERE appid='fulltextsearch';

**Comment by Omaha2002** [comment]
Fixed, indexing again!
