### ISSUE TITLE
Symfony & elasticsearch error Command "fulltextsearch:index" is not defined

### ISSUE THREAD

**Issue by illuzion28** [nextcloud/fulltextsearch_elasticsearch#13]
Hello,
NextCloud 13 and Elasticsearch.

i have this error when i try a manual indexation : 

# sudo -u www-data php ./occ fulltextsearch:index

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "fulltextsearch:index" is not defined.
  Did you mean one of these?
      files_fulltextsearch:configure
      fulltextsearch_elasticsearch:configure

Any idea ?

Thanks 👍

**Comment by daita** [comment]
Check that the app is enabled
