### ISSUE TITLE
Everything is running but nothing get indexed

### ISSUE THREAD

**Issue by saveip** [nextcloud/fulltextsearch_elasticsearch#14]
Dear Team,
We have been running on Nextcloud 12 with Nextant/Solr so far.
After upgrading to Nextcloud 13 we also switched over to Fulltextsearch/Elasticsearch 
All components are running fine as far as we can see, but nevertheless nothing goes into the 
index when we run 

sudo -u www-data php /var/www/nextcloud/occ fulltextsearch:index

output is:
indexing Files.
 USER: cs
- RAM: 21.302200317383
 USER: erm
 USER: mv
- RAM: 22.996002197266
 USER: root
 USER: rwehrenberg
 USER: sth

... so it seems to do something.

Nevertheless nothing is going into the index of Elasticsearch

curl -XGET 'localhost:9200/_cat/indices?v'   says:
health status index     uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   nextcloud myAnZkOJReGSKT4VC8e8qQ   5   1          0            0      2.5kb          2.5kb

We have tried everything but we can not get it to work. Cloud you give as a hand to find the solution ?
We would appreciate it very much.  We urgently need our search engine again ;-)

Thanks in advance
Steffen Hofmann

**Comment by greatwitenorth** [comment]
I had a similar issue and I found that resetting the index helped:

```
sudo -u www-data php /var/www/nextcloud/occ fulltextsearch:reset
sudo -u www-data php /var/www/nextcloud/occ fulltextsearch:index
```
