### ISSUE TITLE
Deleted files are not removed from index

### ISSUE THREAD

**Issue by spbriggs** [nextcloud/fulltextsearch_elasticsearch#15]
Steps to reproduce

Upload some files to Nextcloud
Run php ./occ fulltextsearch:index
Delete some of the files from Nextcloud
Run php ./occ fulltextsearch:index again
Search in Nextcloud web GUI for deleted files

Expected outcome

Deleted files no longer appear in search results

Actual outcome

Deleted files appear in search results

**Comment by daita** [comment]
Should be fixed in 0.7
