### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by Gutz-Pilz** [nextcloud/fulltextsearch_elasticsearch#16]
i get this error when trying to initialy index my files
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 19058208 bytes) in /var/www/html/custom_apps/fulltextsearch_elasticsearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 578`

i am using the latest elasticsearch including ingest-attachment
Nextcloud is 13.0.1 Apache with docker-compose behind nginx reverseproxy

**Comment by daita** [comment]
Try decreasing the size of the chunk from the Settings Page

**Comment by Gutz-Pilz** [comment]
solved
`docker exec --user www-data cloud-app-hm php -d memory_limit=512M occ fulltextsearch:index`

**Comment by angyen** [comment]
> 

How to set the size of chunk. I can't find the Setting page of fulltextsearch
