### ISSUE TITLE
Feature request: Change analysis

### ISSUE THREAD

**Issue by whlsxl** [nextcloud/fulltextsearch_elasticsearch#20]
Hope can change analysis.
I use Chinese, need Chinese tokenizer. I just can change the source code, and copy to docker.

**Comment by daita** [comment]
Can you provide more information about this code you want to change ?

**Comment by daita** [comment]
This is interesting, I will add an option in the settings page.

Thanks for your report !

**Comment by whlsxl** [comment]
Maybe open all the setting body is better😁😁😁

**Comment by daita** [comment]
Well, in a way, you might be right, but I prefer to make this editable in an easy way from the Setting page, than provide a full array.

This should be available in the next version of the fulltextsearch_elasticsearch. However, you will need to add the tokenizer to your elasticsearch

**Comment by daita** [comment]
The last release Full text search - Elasticsearch (v0.7.1) should allows you to index your document
