### ISSUE TITLE
Search hangs at "Searching other places" but works in Kibana

### ISSUE THREAD

**Issue by b-** [nextcloud/fulltextsearch_elasticsearch#22]
Something appears to be wrong, somewhere between my Nextcloud and my ElasticSearch. 
When I enter a query, it hangs at "Searching other places" and I don't see anything relevant in my logs, though I may be overlooking something.

I can use Kibana to manually query the index, and it gives me results (though I _did_ have to increase the timeout in Kibana).

If I do a search via the cli interface, it comes back _instantly_ and I get even less information:

```
root@c:/var/www# sudo -u www-data nextcloud/occ fulltextsearch:search blr@ieitransit.com  '"grade crossing"'
search
root@c:/var/www#
```

I enabled debug logging before doing the above, and the logs say:

```json
{
  "reqId": "pfR4srD8aCxFsoVHsW5W",
  "level": 1,
  "time": "2018-05-06T12:42:15-04:00",
  "remoteAddr": "",
  "user": "--",
  "app": "admin_audit",
  "method": "--",
  "url": "--",
  "message": "Console command executed: fulltextsearch:search blr@ieitransit.com \"grade crossing\"",
  "userAgent": "--",
  "version": "13.0.2.1"
}
```

It doesn't even seem to be hitting the Elastic database, because it comes back far too fast — the default timeout in Kibana of 30 seconds was actually not enough for it to return my results.

Thank you!

EDIT: Perhaps I should mention that I am indexing a dataset of various kinds of files, mounted via samba client smb over `fstab`:
```fstab
## Windows Shares
//<server>/Q-Data/shared	/NetShares/v	cifs	credentials=/NetShares/.smbcredentials,iocharset=utf8,sec=ntlm,file_mode=0777,dir_mode=0777	0	0
//<server>/R-Data		/NetShares/r	cifs	credentials=/NetShares/.smbcredentials,iocharset=utf8,sec=ntlm,file_mode=0777,dir_mode=0777	0	0
//<server>/J-Data		/NetShares/j	cifs	credentials=/NetShares/.smbcredentials,iocharset=utf8,sec=ntlm,file_mode=0777,dir_mode=0777	0	0
//<server>/W-Data		/NetShares/w	cifs	credentials=/NetShares/.smbcredentials,iocharset=utf8,sec=ntlm,file_mode=0777,dir_mode=0777	0	0
```

**Comment by b-** [comment]
Screenshot from Kibana: 
![screen shot 2018-05-06 at 12 50 27 pm](https://user-images.githubusercontent.com/284789/39675652-387d8350-512c-11e8-8544-c937c03d31fd.png)

**Comment by daita** [comment]
is your first index finished ?

**Comment by b-** [comment]
...I don’t think so. Indexing hung as soon as it started with the next user. 

I’m trying to index 500 GB of data where nearly 100 GB has extractable text. If I do `occ fulltextsearch:index` will it continue where it left off? Or do I actually need to `fulltextsearch:reset` if it didn’t finish the first time?

**Comment by daita** [comment]
you can go on with the index with ```./occ fulltextsearch:index``` and it will start again where it stopped.

**Comment by b-** [comment]
It should, but it doesn’t. I get that repeating RAM line. I left it for over 24 hours.

**Comment by daita** [comment]
Please try with the new version, do a full reset and index.

**Comment by joergmschulz** [comment]
Hello, 
Thank You!

Just deleted the three folders and reinstalled from the AppStore.

php ../occ app:list |grep fullt
  - files_fulltextsearch: 0.7.0
  - fulltextsearch: 0.7.0
  - fulltextsearch_elasticsearch: 0.7.0

php ../occ fulltextsearch:index
(many successful messages)

Files are indexed and found for
- users with DOT in the names

but: 
Groupfolders are not (yet) indexed.

**Comment by daita** [comment]
Any update ?
