### ISSUE TITLE
Nextcloud 25 support

### ISSUE THREAD

**Issue by jacotec** [nextcloud/fulltextsearch_elasticsearch#228]
Nextcloud 25 is out a while and the fulltextsearch apps are currently blocking my update ...

**Comment by arnowelzel** [comment]
The fulltext apps work fine in NC 25 as well - just enable them manually to override the compatibility warning and activate them.

**Comment by martadinata666** [comment]
Do we also need manually apply patch here? https://github.com/nextcloud/files_fulltextsearch/pull/170 because last time, also need manual patch instead of new release cut.

**Comment by p-bo** [comment]
It seems to be resolved now: https://apps.nextcloud.com/apps/fulltextsearch_elasticsearch/releases?platform=25#25

**Comment by pktiuk** [comment]
@jacotec    
I think this issue should  be closed now.
