### ISSUE TITLE
Compability for NC 26

### ISSUE THREAD

**Issue by RunnerLexico** [nextcloud/fulltextsearch_elasticsearch#245]
Nextcloud 26 is out and the fulltextsearch apps are not compatible yet.

Does it work with Nextcloud 26?

Thanks and regards

**Comment by pktiuk** [comment]
Has anyone tested it with NC 26?

**Comment by oechsler** [comment]
@pktiuk I have. It works flawless.

Here is what I'am running:

```bash
php occ status
  - installed: true
  - version: 26.0.1.1
  - versionstring: 26.0.1
  - edition: 
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false
```

```bash
php occ fulltextsearch:check  
Full text search 25.0.0
 
- Search Platform:
Elasticsearch 25.0.0 (Selected)
{
    "elastic_host": [
        "http://nextcloud-aio-fulltextsearch:9200"
    ],
    "elastic_index": "nextcloud-aio",
    "fields_limit": "10000",
    "es_ver_below66": "0",
    "analyzer_tokenizer": "standard"
} 

- Content Providers:
Files 25.0.0
{
    "files_local": "1",
    "files_external": "0",
    "files_group_folders": "0",
    "files_encrypted": "0",
    "files_federated": "0",
    "files_size": "20",
    "files_pdf": "1",
    "files_office": "1",
    "files_image": "0",
    "files_audio": "0"
}
```

With that indexing completed successfully

```bash
php occ fulltextsearch:index

Options: []
Memory: 36 MB
┌─ Indexing  ────
│ Action: indexDocument
│ Provider: Files                Account: samuel
│ Document: 500
│ Info: application/x-iwork-keynote-sffkey
│ Title: Zertifikate/proxmox.key
│ Content size: 0
│ Chunk:     19/19
│ Progress:    all/1
└──
┌─ Results ────
│ Result:    330/330
│ Index: files:500
│ Status: ok
│ Message: {"_index":"nextcloud-aio","_type":"_doc","_id":"files:500","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":329,"_primary_term":1}
│ 
│ 
└──
┌─ Errors ────
│ Error:      0/0
│ Index: 
│ Exception: 
│ Message: 
│ 
│ 
└──
## x:first result ## c/v:prec/next result ## b:last result
## f:first error ## h/j:prec/next error ## d:delete error ## l:last error
## q:quit ## p:pause
```

**Comment by ShinjiLE** [comment]
*Argh*
As i can see it requires now elasticsearch 8 . 
I running opensearch and it seems only compatible with the elasticsearch api 7.

**Comment by ostasevych** [comment]
> _Argh_ As i can see it requires now elasticsearch 8 . I running opensearch and it seems only compatible with the elasticsearch api 7.

OMG! Where is it documented?.. Which specific version does it require? What about fulltext search OCR, which is now v.25?

**Comment by R0Wi** [comment]
When using the app in versions prior to 26, please use ES 7.X.X. Starting with app version 26, I'd recommend ES 8.6.1, which exactly matches the used ES client version. For upgrading from earlier ES versions, see my comment [here](https://github.com/nextcloud/fulltextsearch_elasticsearch/issues/257#issuecomment-1576101172).

I updated the [Wiki](https://github.com/nextcloud/fulltextsearch_elasticsearch/wiki#installation-of-the-elasticsearch-servlet) accordingly. Please give me some feedback if this helps and feel free to reopen if needed.

**Comment by archont00** [comment]
The [Wiki](https://github.com/nextcloud/fulltextsearch_elasticsearch/wiki#installation-of-the-elasticsearch-servlet) *recommends* using ES 8.6.1, while the full text search client seems to *require* this version.

```
Testing search platform. fail 
In ProductCheckTrait.php line 32:
                                                                                                      
  The client noticed that the server is not Elasticsearch and we do not support this unknown product
```


Would be worth to update the Wiki.

BTW, upgrading ES to a new version is a breaking change - my ES is used by more clients, not supporting 8.x yet...
