### ISSUE TITLE
Error searching in 0.7.1

### ISSUE THREAD

**Issue by kevinkk525** [nextcloud/fulltextsearch_elasticsearch#25]
When searching I get this error in 0.7.1:

{"error":{"root_cause":[{"type":"parsing_exception","reason":"[bool] malformed query, expected [END_OBJECT] but found [FIELD_NAME]","line":1,"col":171}],"type":"parsing_exception","reason":"[bool] malformed query, expected [END_OBJECT] but found [FIELD_NAME]","line":1,"col":171},"status":400}

fulltextsearch_elasticsearch 0.7.1
fulltextsearch 0.7.1

A few people put this error in fulltextsearch repo: [#322](https://github.com/nextcloud/fulltextsearch/issues/322)

**Comment by fa-ribeiro** [comment]
Same here :-(

![image](https://user-images.githubusercontent.com/2636096/40231025-71e49142-5a91-11e8-8b82-ca42fdf26e27.png)

**Comment by daita** [comment]
Fixed: https://github.com/nextcloud/fulltextsearch/issues/321
