### ISSUE TITLE
NC 26 edition does not work with basi auth

### ISSUE THREAD

**Issue by beertje44** [nextcloud/fulltextsearch_elasticsearch#256]
Seems that http(s)://username:password@host:port does not work with the latest elesticsearch php connector. Line 384/385 of fulltextsearch_elasticsearch/lib/Platform/ElasticSearchPlatform.php should read:

`$cb = ClientBuilder::create()
							   ->setHosts($hosts)
							   ->setBasicAuthentication($username, $password)
							   ->setRetries(3);`

Guess you could extract that from the hostname, but since you can provide several hosts, I guess it would be better and easier to add an optional username and password field to the config form? :)

**Comment by baltaner** [comment]
Thanks a lot - its working now!
Same problem here with nc26 and es7.17.10 and readonlyrest-1.48.0_es7.17.10
But in your fix I habe to hardcode username/password - $username/$password doesn't work for me.

**Comment by beertje44** [comment]
Yeah this is just some ducktape ;)

We'll have to wait for the maintainber to respond for a decent fix.

**Comment by depthwise** [comment]
+1 - hardcoded the credentials for now in my instance, and indexing works now.
