### ISSUE TITLE
The client noticed that the server is not Elasticsearch and we do not support this unknown product

### ISSUE THREAD

**Issue by Svedrin** [nextcloud/fulltextsearch_elasticsearch#257]
I was wondering why my ES index doesn't get updated anymore, so I ran `occ fulltextsearch:test`. It greeted me with this error:

```
# occ fulltextsearch:test

.Testing your current setup:
Creating mocked content provider. ok
Testing mocked provider: get indexable documents. (2 items) ok
Loading search platform. (Elasticsearch) ok
Testing search platform. fail
In ProductCheckTrait.php line 32:

  The client noticed that the server is not Elasticsearch and we do not support this unknown product


fulltextsearch:test [--output [OUTPUT]] [-j|--json] [-d|--platform_delay PLATFORM_DELAY]
```

[Google reveals](https://stackoverflow.com/questions/68802324/elasticsearch-in-go-err-the-client-noticed-that-the-server-is-not-elasticsear) that this is because the ES client library checks what it's connecting to, and if the server is not ES8, it will throw this error. Due to #240 my server is ES7, and the client ships with an ES8 library:

https://github.com/nextcloud/fulltextsearch_elasticsearch/blob/fc8da6e73b0d4d42934449c428421a89155e50d4/composer.json#L28-L30

So the client doesn't support ES7, and Nextcloud doesn't support ES8? Am I missing something? Is there a way to get this to work currently? 😕

**Comment by Happyfeet01** [comment]
Same here

`lars@livesystem-debian:~$ sudo -uwww-data php8.2 /var/www/nextcloud/occ fulltextsearch:test

.Testing your current setup:
Creating mocked content provider. ok
Testing mocked provider: get indexable documents. (2 items) ok
Loading search platform. (Elasticsearch) ok
Testing search platform. fail
In Test.php line 304:

  Search platform (Elasticsearch) down ?


fulltextsearch:test [--output [OUTPUT]] [-j|--json] [-d|--platform_delay PLATFORM_DELAY]

lars@livesystem-debian:~$ sudo -uwww-data php8.2 /var/www/nextcloud/occ fulltextsearch:check
Full text search 26.0.0

- Search Platform:
Elasticsearch 26.0.0 (Selected)
{
    "elastic_host": [
        "http://internesuche:********@127.0.0.1:9200"
    ],
    "elastic_index": "internesuche",
    "fields_limit": "10000",
    "es_ver_below66": "0",
    "analyzer_tokenizer": ""
}

- Content Providers:
Deck 1.9.0
[]
Files 26.0.0
{
    "files_local": "1",
    "files_external": "0",
    "files_group_folders": "0",
    "files_encrypted": "0",
    "files_federated": "0",
    "files_size": "10",
    "files_pdf": "1",
    "files_office": "1",
    "files_image": "0",
    "files_audio": "0",
    "files_chunk_size": "2",
    "files_fulltextsearch_tesseract": {
        "version": "25.0.0",
        "enabled": "1",
        "psm": "4",
        "lang": "de,eng",
        "pdf": "1",
        "pdf_limit": "0"
    }
}`

But with the live command I got this

![IMG_20230510_112657.jpg](https://github.com/nextcloud/fulltextsearch_elasticsearch/assets/3295104/a2a6fe9d-1533-4cb6-843e-e8da4d8038ca)

**Comment by R0Wi** [comment]
I recently upgraded to NC26 and I was able to get FTS working again. I'm using ES server `8.6.1` via Docker (see https://github.com/R0Wi/elasticsearch-nextcloud-docker) and this combination seems to work pretty well.

Note: if you have to upgrade from an earlier ES version and you don't want to loose your index data, use [this upgrade guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html). In my case I restarted the cluster once with version 7.17 to apply all migrations, then upgraded to 8.6.1.

**Comment by ostasevych** [comment]
> I recently upgraded to NC26 and I was able to get FTS working again. I'm using ES server `8.6.1` via Docker (see https://github.com/R0Wi/elasticsearch-nextcloud-docker) and this combination seems to work pretty well.
> 
Which version of the full text search - Elasticsearch platform do you use? Is it 25.0 or 26.0?

> Note: if you have to upgrade from an earlier ES version and you don't want to loose your index data, use [this upgrade guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html). In my case I restarted the cluster once with version 7.17 to apply all migrations, then upgraded to 8.6.1.

Please, explain, how to do it properly.

**Comment by R0Wi** [comment]
> Which version of the full text search - Elasticsearch platform app do you use? Is it 25.0 or 26.0?

I'm using NC 26 together with the Fulltext Search Apps on version 26, too. Elasticsearch Server is on `8.6.1`.

> Please, explain, how to do it properly.

In my case I came from Elasticsearch `7.6.x` (together with NC 25). I initially used [this docker-compose](https://github.com/R0Wi/elasticsearch-nextcloud-docker/blob/062b66ab066d71d4d509c9e8faf21ce7957e621b/docker-compose.yml) with version `7.6.1` in the `.env`-file. I stopped the cluster and changed the version to `7.17.0` and restarted the cluster again (with the same volume, containing the `7.6.1` index data. If you want to be safe, create a backup of the docker volume before). I then waited for the cluster to be fully started (`docker logs` tells me that the cluster turned from state "red" to "yellow"). Then again stop that cluster and change the version to `8.6.1` in the `.env`-file. Restart, wait and you should be fine.

Like I said please also be aware of the [official upgrade guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html), since in theory there could be breaking changes (which I did not observe for the NC index). If you're uncertain, just use a new, empty docker volume and recreate your index via `php occ fulltextsearch:index`. Hope this helps!

**Comment by Svedrin** [comment]
Indeed, using ES 8.6.1 works :tada: 

However, first I noticed that the ES client couldn't login to the ES cluster (tcpdump revealed that it didn't even send an `Authorization` header), and after I nuked the cluster to make sure I didn't have any passwords wrong, the cluster came up with SSL enabled and there was no option to have it accept a self-signed cert. So I tried disabling authentication and SSL by adding these two env vars to the ES container:

```
xpack.security.enabled=false
xpack.security.http.ssl.enabled=false
```

This worked, now `occ fulltextsearch:test` works and it's currently indexing.
