### ISSUE TITLE
user credentials supported in elastic search URL  ?

### ISSUE THREAD

**Issue by zkhan93** [nextcloud/fulltextsearch_elasticsearch#258]
I'm on nextcloud v26.0.1

I had to use externally hosted elastic search instance so I'm trying to provide user and pass as part of URL in settings 
`https://nextcloud:secret@elasticsearch.example.in`
however the line [here](https://github.com/nextcloud/fulltextsearch_elasticsearch/blob/3aefd84c0f05fe82509547b214d210bb87064358/lib/Platform/ElasticSearchPlatform.php#LL107C57-L107C57) seems to not respect the password provided in the URL

and ./occ fulltextsearch:test fails with HTTP status 403 

I just want to confirm that that password is being send over to elastic search.

**Comment by beertje44** [comment]
See: https://github.com/nextcloud/fulltextsearch_elasticsearch/issues/256

Will try to provide a patch later, all of this is not rocketsience :)

**Comment by R0Wi** [comment]
PR is here https://github.com/nextcloud/fulltextsearch_elasticsearch/pull/261

**Comment by matt-alton** [comment]
> PR is here #261

After several weeks looking at this on and off and many internet searches and expetives later this PR has made ES8 and NC26 finally begin indexing.

Thank you!

**Comment by R0Wi** [comment]
Closing this since it seems to be resolved by #261
