### ISSUE TITLE
Error in v0.7.1

### ISSUE THREAD

**Issue by ettingerkarl** [nextcloud/fulltextsearch_elasticsearch#26]
Error in v0.7.1
{"error":{"root_cause":[{"type":"parsing_exception","reason":"[bool] malformed query, expected [END_OBJECT] but found [FIELD_NAME]","line":1,"col":171}],"type":"parsing_exception","reason":"[bool] malformed query, expected [END_OBJECT] but found [FIELD_NAME]","line":1,"col":171},"status":400}

In v0.7.0 is OK

**Comment by joergmschulz** [comment]
Duplicate.
Fixed: nextcloud/fulltextsearch#321
will appear in the appstore one of these days....
