### ISSUE TITLE
Compatibility with EC 8: Update Wiki

### ISSUE THREAD

**Issue by ann0see** [nextcloud/fulltextsearch_elasticsearch#264]
Is this App compatible with Elasticsearch 8? The Wiki seems to be unmaintained. I've installed EC 8 on my Debian Server but haven't tested if everything works as expected - especially the [Tesseract OCR plugin](https://apps.nextcloud.com/apps/files_fulltextsearch_tesseract)

From my first sight, it seems as if ingest-attachment is not a plugin but rather an (already included?) module:

```
$ /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-attachment
-> Installing ingest-attachment
[ingest-attachment] is no longer a plugin but instead a module packaged with this distribution of Elasticsearch
-> Please restart Elasticsearch to activate any plugins installed
```

I believe this should be updated in the wiki once verified that the plugin works.

**Comment by grey-golem** [comment]
Agree. I am looking for instructions on working with Elasticsearch 8. The relevant page here is from 2018.

**Comment by R0Wi** [comment]
I added a deprecation note to https://github.com/nextcloud/fulltextsearch_elasticsearch/wiki#ingest-attachment. Are there any other instructions not working with ES8? In general app versions starting from 26 should be used with ES 8.6.1, at least in my case this works quite well (my comment [here](https://github.com/nextcloud/fulltextsearch_elasticsearch/issues/257#issuecomment-1576101172) might help aswell)

**Comment by ann0see** [comment]
I've uninstalled EC 8 and the plugin for now - but might install it in future again. Closing this issue as I'm no longer actively behind it.
