### ISSUE TITLE
Word in top of line did not match (CR/LF was escaped in the content field)

### ISSUE THREAD

**Issue by hankei6km** [nextcloud/fulltextsearch_elasticsearch#27]
Hello,
I'm not good at English.
And I am a beginner of Elastic search.
Sorry if there is a strange expression.

## Environment
- Nextcloud 13.0.2 fpm([official docker image](https://hub.docker.com/_/nextcloud/))
- FullTextSearch\_ElasticSearch  0.7.2
- Files\_FullTextSearch 0.7.2
- FullTextSearch 0.7.2
- Elastic search 5.6.9(docker image created with Dokcerfile instructed by [the wiki](https://github.com/nextcloud/fulltextsearch/wiki/Basic-Installation)) and 6.2.4([docker iamge](https://www.docker.elastic.co/))
- Settings Elastic Search
    - Address of the Servlet: http://index:9200/
    - Index: my\_index
    - Analyzer tokenizer: 

## Steps to reproduce
- Create the following text file on Nextcloud Web UI.
```
one
two
- three
```
- Index document(occ fulltextsearch:index).
- Enter "two" in the seach word on full text search panel.
- The created file does not match

Morever, enter "three", it matches.

## Workaround

`CR/LF` (and any ctrl chars. ie. `TAB`) was escaped in `content` filed by `set` processor.

```
  "_source" : {
    ...
    "content" : "one\\r\\ntwo\\r\\n- three",
    ...
  }
```

Anyway, I tried using `convert` processor instead of `set` processor.
https://github.com/hankei6km/fulltextsearch_elasticsearch/commit/8c8283582bff5507eeaa116e6fc0a23b0ca43511

```
  "_source" : {
    ...
    "content" : "one\r\ntwo\r\n- three",
    ...
  }
```

It seems that they match correctly.

**Comment by hankei6km** [comment]
Unfortunately, I understand only the description of the [Convert Processor document](https://www.elastic.co/guide/en/elasticsearch/reference/current/convert-processor.html).

If I was to say it,  I am concerned about when conversion failed.

> If a provided field cannot be appropriately converted, the Convert Processor will still process successfully and leave the field value as-is. In such a case, target_field will still be updated with the unconverted field value.


FYI
I tried rough measurements of running time of `set` and `convert`.
(it was a noisy environment(running some VMs on my Hyper-V server), the accuracy of the result is low)

## Environment
- Docker on VM(Arch linux) on Hyper-V Server
- CPU: Core i5-4200M
- MEM: 16G
- HDD: 500G(5400rpm)

## Sample Data
- About 1500 `*.md` files(total size 4.7MB).


## Procedure
Repeat the following procedure three times.

- Reset index(`occ fulltextsearch:reset`).
- Run `time sudo -u www-data php occ fulltextsearch:index`.
- Apply "convert" patch to "fulltextsearch_elasticsearch".
- Reset index(`occ fulltextsearch:reset`).
- Run `time sudo -u www-data php occ fulltextsearch:index`.
- Revert "fulltextsearch_elasticsearch" to master.


## Results
processor  | 1 | 2 | 3
--------|--------------------------------|--------------------------------|------------------------
set     | 17m 40.02s<br>0m 48.60s<br>0m 10.18s | 17m 26.86s<br>0m 49.25s<br>0m 10.32s | 16m 53.87s<br>0m 48.46s<br>0m 10.16s
convert | 17m 10.20s<br>0m 48.85s<br>0m 10.25s | 16m 40.84s<br>0m 48.10s<br>0m 10.24s | 25m 5.47s<br>0m 52.50s<br>0m 11.07s

**Comment by daita** [comment]
That last result :)

Can you PR your edit ?

**Comment by hankei6km** [comment]
Thank you for your quick merge.
