### ISSUE TITLE
Error: Call to a member function findBookmarks() on null in /var/www/html/nextcloud/apps/bookmarks_fulltextsearch/lib/Service/BookmarksService.php:85

### ISSUE THREAD

**Issue by laTruffe79** [nextcloud/fulltextsearch_elasticsearch#33]
Hello,
I'm trying to index my documents with the command 
`sudo -u www-data php ./occ fulltextsearch:index
`
But all I got is this Exception : 
>  Error: Call to a member function findBookmarks() on null in /var/www/html/nextcloud/apps/bookmarks_fulltextsearch/lib/Service/BookmarksService.php:85

Did you have any idea where is the problem ? (I'v created some bookmarks so why did he says that the function is applied on null and why there is an exception on null?)

Thanks for your help.

**Comment by daita** [comment]
Fixed in 0.8.0

**Comment by laTruffe79** [comment]
Thanks, great work ! ^_^
