### ISSUE TITLE
update problem (29.0.0.)

### ISSUE THREAD

**Issue by prolibre** [nextcloud/fulltextsearch_elasticsearch#368]
An update is proposed (29.0.0) but fails because the file does not exist.

`404 Not Found` response:\nNot Found\n", "exception":{}, "CustomMessage": "Client error: `GET https://github.com/nextcloud-releases/fulltextsearch_elasticsearch/releases/download/29.0.0/fulltextsearch_elasticsearch-29.0.0.tar.gz` resulted in a `404 Not Found` response:\nNot Found\n"}}`

**Comment by bovender** [comment]
+1

**Comment by JameZUK** [comment]
++1

**Comment by EVOTk** [comment]
Same

**Comment by FloTheSysadmin** [comment]
Same

**Comment by kmorber** [comment]
same

**Comment by rcfa** [comment]
same, arm64

**Comment by Kdubs937** [comment]
Same issue.  Full text Search also breaks the cronjob and I had to disable it.

**Comment by D3nnis3n** [comment]
Here as well

**Comment by prolibre** [comment]
repaired yesterday

**Comment by EVOTk** [comment]
I successfully updated, thank you
