### ISSUE TITLE
Ingesting outlook .msg files

### ISSUE THREAD

**Issue by FLanganke** [nextcloud/fulltextsearch_elasticsearch#37]
Hi,

i've been testing with the current release available on nextcloud. The indexing works great on PDF's but the index does not contain the .msg files on my nextcloud drive.
The apache tika does provide .msg content, is this data not processed yet? Did i miss any configuration?

Thanks!

**Comment by daita** [comment]
can you provide me with a non-sensitive .msg file : maxence@nextcloud.com
