### ISSUE TITLE
compatibility issues with newest elasticsearch version

### ISSUE THREAD

**Issue by mudi0** [nextcloud/fulltextsearch_elasticsearch#377]
### Issue: Default Mapping and Setting of Elasticsearch is Not Compatible with Newest Elasticsearch Version

**Elasticsearch Version:** 8.14.2  
**FullTextSearch Version:** 29.0.0  
**FullTextSearch_Elasticsearch Version:** 29.0.1

#### Steps to Reproduce:

1. **Adjust Elasticsearch Loglevel:**
   ```sh
   nano /etc/elasticsearch/log4j2.properties
   ```

   Set the log level to debug:
   ```sh
   rootLogger.level = debug
   ```

2. **Reset and Reindex FullTextSearch:**
   ```sh
   sudo -u www-data php /var/www/nextcloud/occ fulltextsearch:reset
   sudo -u www-data php /var/www/nextcloud/occ fulltextsearch:index
   ```

3. **Check the Elasticsearch Log for Errors:**
   ```sh
   tail -f /var/nextcloud_data/nextcloud.log
   ```

#### Observed Behavior:
During the index creation, the process runs into an exception as seen in the Elasticsearch log file:
[elasticsearch logfile.txt](https://github.com/user-attachments/files/16158012/elasticsearch.logfile.txt)

#### Error Message:
```
Failed to parse mapping: Root mapping definition has unsupported parameters: [standard: {dynamic=true, properties={owner={type=keyword}, groups={type=keyword}, circles={type=keyword}, metatags={type=keyword}, source={type=keyword}, title={copy_to=combined, analyzer=keyword, term_vector=with_positions_offsets, type=text}, content={copy_to=combined, analyzer=analyzer, term_vector=with_positions_offsets, type=text}, users={type=keyword}, tags={type=keyword}, provider={type=keyword}, subtags={type=keyword}, links={type=keyword}, combined={analyzer=analyzer, term_vector=with_positions_offsets, type=text}, hash={type=keyword}}}]
```

#### Analysis:
The mapping and setting of the index are defined in the following file, which appear to be incompatible with the latest version of Elasticsearch:
`lib/Service/IndexMappingService.php`

#### Request:
Please update the FullTextSearch and FullTextSearch_Elasticsearch apps to be compatible with Elasticsearch version 8.14.2.

**Comment by XueSheng-GIT** [comment]
Sounds like https://github.com/nextcloud/fulltextsearch_elasticsearch/issues/329.
@mudi0 please double check whether your issue is different to this. if not, I suggest to close this issue.

**Comment by mudi0** [comment]
OK, you can close it.

**Comment by XueSheng-GIT** [comment]
@mudi0, I do not have the rights to close it. But you can do it yourself.
