### ISSUE TITLE
Upon occ fulltextsearch:index Nextcloud 13.0.6 reports Undefined index: more at /var/www/html/apps/fulltextsearch_elasticsearch/lib/Service/SearchService.php#192

### ISSUE THREAD

**Issue by herrep** [nextcloud/fulltextsearch_elasticsearch#40]
Hi,

I installed fulltextsearch and the related addons like fulltextsearch_elasticsearch. Elasticsearch is version 6.4.1 and accessible. I can also run occ fulltextsearch:test with proper output. However, when trying to start building an index, I receive the following log entry at Nextcloud:

Undefined index: more at /var/www/html/apps/fulltextsearch_elasticsearch/lib/Service/SearchService.php#192

The occ output remains at Generating index 0/0 and I cannot leave the user interface. I need to terminate the terminal session.

Best regasrds,
Peter

**Comment by daita** [comment]
thanks for the report.
