### ISSUE TITLE
shared folders index issue

### ISSUE THREAD

**Issue by damac23** [nextcloud/fulltextsearch_elasticsearch#43]
Plugin-Version: 1.0.2
NextCloud-Version: 14.0.4

If I share a folder to a user that is in the alphabetical order before my user, the contents cannot be indexed. It runs pretty fast through the list always with "Content size: 0".
And when it's finally in my "Account: ZZZ" it won't try to index the files again. So I can only search through PDF-files within none-shared folders.

Any idea on how to prevent that?

**Comment by daita** [comment]
can you confirm the bug is still in the last version of full text search ?

**Comment by damac23** [comment]
Great!
It's now working - tested with this combo:
NextCloud: 15.0.4
Plugin: 1.2.3
