### ISSUE TITLE
Get error when indexing external storage ( SMB )

### ISSUE THREAD

**Issue by hoangdinhanphabe** [nextcloud/fulltextsearch_elasticsearch#46]
I Got this error 
Protocol negotiation failed: NT_STATUS_CONNECTION_RESET

I'm Using nextcloud 15 

![image](https://user-images.githubusercontent.com/42403971/51958542-fc5fdc80-2482-11e9-8e15-425937e57d5d.png)

**Comment by daita** [comment]
What is the setup of your external storage ?

**Comment by hoangdinhanphabe** [comment]
I fixed that problem by enable SMB ( v1) on my Windows Server
