### ISSUE TITLE
pipeline with id [attachment] does not exist

### ISSUE THREAD

**Issue by bkanuka** [nextcloud/fulltextsearch_elasticsearch#6]
I'm getting this error when running `fulltextsearch:index`

```
[Elasticsearch\Common\Exceptions\BadRequest400Exception]                                                                                                  
  {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"pipeline with id [attachment] does not exist"}],"type":"illegal_argument_exceptio  
  n","reason":"pipeline with id [attachment] does not exist"},"status":400}
```

I have the ingest-attachment plugin installed in elasticsearch.

**Comment by bkanuka** [comment]
I had to initialize the attachment pipeline by PUT to _ingest/pipeline/attachment

```
{
  "description" : "Extract attachment information",
  "processors" : [
    {
      "attachment" : {
        "field" : "content",
        "indexed_chars" : -1
      }
    }
  ]
}
```

I think the fix would be to do this automatically...or put this in the README as a minimum.

**Comment by daita** [comment]
This should be created during your first index

**Comment by bkanuka** [comment]
It wasn't.  And did I get that initialization command right? Because I'm not getting any search results. Not sure if its the same issue or a different one.

**Comment by daita** [comment]
you should reset first:

>      ./occ fulltextsearch:reset
>      ./occ fulltextsearch:index

**Comment by bkanuka** [comment]
you're right. that initializes the index automatically (in case something went wrong)
Now I'm still not getting any results...but that's a different issue
