### ISSUE TITLE
Elastic Search throws an error with Ubuntu Snap

### ISSUE THREAD

**Issue by gevera** [nextcloud/fulltextsearch_elasticsearch#9]
**Distribution**

Description: Ubuntu 16.04.3 LTS
Release: 16.04
Codename: xenial
Linux localhost 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Nextcloud**

nextcloud  12.0.4snap1  4371  nextcloud

`name:      nextcloud
summary:   Nextcloud Server - A safe home for all your data
publisher: nextcloud
contact:   https://github.com/nextcloud/nextcloud-snap
description: |
  Access, share and protect your files, calendars, contacts, communication and
  more at home and in your enterprise.

commands:
  - nextcloud.disable-https
  - nextcloud.enable-https
  - nextcloud.manual-install
  - nextcloud.mysql-client
  - nextcloud.mysqldump
  - nextcloud.occ
services:
  nextcloud.apache:         simple, enabled, active
  nextcloud.mdns-publisher: simple, enabled, active
  nextcloud.mysql:          simple, enabled, active
  nextcloud.nextcloud-cron: simple, enabled, active
  nextcloud.php-fpm:        simple, enabled, active
  nextcloud.redis-server:   simple, enabled, active
  nextcloud.renew-certs:    simple, enabled, active
tracking:                   stable
installed:                  12.0.4snap1 (4371) 192MB -
refreshed:                  2017-12-12 16:52:42 -0700 MST
channels:                                            
  stable:                   12.0.4snap1       (4371) 192MB -
  candidate:                12.0.4snap1       (4371) 192MB -
  beta:                     12.0.4snap1       (4474) 192MB -
  edge:                     master-2018-01-19 (4811) 192MB -
  11/stable:                11.0.6snap1       (4724) 191MB -
  11/candidate:             11.0.6snap1       (4724) 191MB -
  11/beta:                  11.0.6snap1       (4724) 191MB -
  11/edge:                  11-2018-01-19     (4808) 191MB -
  12/stable:                –                              
  12/candidate:             –                              
  12/beta:                  –                              
  12/edge:                  12-2018-01-19     (4807) 192MB -
  13/stable:                –                              
  13/candidate:             13.0.0-rc1snap1   (4781) 192MB -
  13/beta:                  ↑                              
  13/edge:                  ↑ `

**Elastic Search**

`elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-01-19 14:36:26 MST; 39min ago
     Docs: http://www.elastic.co
 Main PID: 1207 (java)
    Tasks: 30
   Memory: 1.2G
      CPU: 16.365s
   CGroup: /system.slice/elasticsearch.service
           └─1207 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTo
`
`HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 432

{
  "name" : "aILxsCe",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "Kodmo23LdSYdfs0ancpTNpcWg",
  "version" : {
    "number" : "6.1.2",
    "build_hash" : "12a1fed5",
    "build_date" : "2018-01-10T02:35:59.208Z",
    "build_snapshot" : false,
    "lucene_version" : "7.1.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
`

**The Error Log from Nextcloud**

`include(): Failed opening 'fulltextsearch_elasticsearch/lib/admin.php' for inclusion (include_path='/snap/nextcloud/4371/htdocs/3rdparty/pear/console_getopt:/snap/nextcloud/4371/htdocs/3rdparty/pear/pear_exception:/snap/nextcloud/4371/htdocs/3rdparty/pear/archive_tar:/snap/nextcloud/4371/htdocs/3rdparty/pear/pear-core-minimal/src:/snap/nextcloud/current/htdocs/apps:/var/snap/nextcloud/current/nextcloud/extra-apps') at /snap/nextcloud/4371/htdocs/lib/private/legacy/app.php#702`

`
include(fulltextsearch_elasticsearch/lib/admin.php): failed to open stream: No such file or directory at /snap/nextcloud/4371/htdocs/lib/private/legacy/app.php#702 `

**Comment by daita** [comment]
should be fixed next release

**Comment by gevera** [comment]
Awesome. Can't wait for it.
