### ISSUE TITLE
Not a bug; just an info

### ISSUE THREAD

**Issue by derritter88** [nextcloud/fulltextsearch_elasticsearch#96]
Today I moved to encrypted Elasticsearch with the build-in xpack stuff.
As expected Fulltextsearch stopped working.

To solve this problem I have added my freshly generated elasticsearch root certificate to my local trusted ca store + to the nextcloud certificate store.

After that it works again.

**Comment by fwolfst** [comment]
@derritter88 Sorry, but this should be closed. It will still be found via search engines, but would reduce the issue list. One could create a real todo from it (better error message?), but I think there are more pressing issues.

**Comment by derritter88** [comment]
@fwolfst: Sure - I'll close it.
